"use client";

import { useState } from "react";
import { Copy, PackageCheck } from "lucide-react";

import { Button } from "@/components/ui/button";
import type { AnimationExportPackage } from "@/types/exportPackage";
import type { StoryboardScene } from "@/types/storyboard";

type ExportPackagePanelProps = {
  exportPackage: AnimationExportPackage;
  scenes: StoryboardScene[];
};

export default function ExportPackagePanel({
  exportPackage,
  scenes,
}: ExportPackagePanelProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const hashtags = exportPackage.hashtags.join(" ");

  const allScenePrompts = scenes
    .map((scene) => {
      return `Scene ${scene.sceneNumber} (${scene.duration})

${scene.videoPrompt}`;
    })
    .join(`

-----------------------------

`);

  const allVoiceOver = scenes
    .map((scene) => {
      return `Scene ${scene.sceneNumber} (${scene.duration})

${scene.narration}`;
    })
    .join(`

-----------------------------

`);

  const fullExportPackage = `TITLE:
${exportPackage.title}

DESCRIPTION:
${exportPackage.description}

CAPTION:
${exportPackage.caption}

HASHTAGS:
${hashtags}

THUMBNAIL TEXT:
${exportPackage.thumbnailText}

PINNED COMMENT:
${exportPackage.pinnedComment}

CALL TO ACTION:
${exportPackage.callToAction}

SCENE PROMPTS:
${allScenePrompts}

VOICE OVER:
${allVoiceOver}`;

  function copyText(text: string, label: string) {
    navigator.clipboard.writeText(text);

    setCopied(label);

    setTimeout(() => {
      setCopied(null);
    }, 1500);
  }

  return (
    <div
      id="export-package-panel"
      className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-900 p-6"
    >
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-3">
            <PackageCheck className="text-blue-500" size={28} />

            <h2 className="text-2xl font-semibold text-white">
              AI Export Package
            </h2>
          </div>

          <p className="mt-2 text-zinc-400">
            Publishing package generated by Gemini.
          </p>
        </div>

        <Button
          onClick={() => copyText(fullExportPackage, "all")}
          className="bg-blue-600 hover:bg-blue-500"
        >
          <Copy size={18} />
          {copied === "all" ? "Copied" : "Copy All Export"}
        </Button>
      </div>

      <div className="mt-6 space-y-5">
        <ExportItem
          label="Title"
          value={exportPackage.title}
          copied={copied === "title"}
          onCopy={() => copyText(exportPackage.title, "title")}
        />

        <ExportItem
          label="Description"
          value={exportPackage.description}
          copied={copied === "description"}
          onCopy={() => copyText(exportPackage.description, "description")}
        />

        <ExportItem
          label="Caption"
          value={exportPackage.caption}
          copied={copied === "caption"}
          onCopy={() => copyText(exportPackage.caption, "caption")}
        />

        <ExportItem
          label="Hashtags"
          value={hashtags}
          copied={copied === "hashtags"}
          onCopy={() => copyText(hashtags, "hashtags")}
        />

        <ExportItem
          label="Thumbnail Text"
          value={exportPackage.thumbnailText}
          copied={copied === "thumbnail"}
          onCopy={() => copyText(exportPackage.thumbnailText, "thumbnail")}
        />

        <ExportItem
          label="Pinned Comment"
          value={exportPackage.pinnedComment}
          copied={copied === "pinned"}
          onCopy={() => copyText(exportPackage.pinnedComment, "pinned")}
        />

        <ExportItem
          label="Call To Action"
          value={exportPackage.callToAction}
          copied={copied === "cta"}
          onCopy={() => copyText(exportPackage.callToAction, "cta")}
        />

        <ExportItem
          label="All Scene Prompts"
          value={allScenePrompts}
          copied={copied === "prompts"}
          onCopy={() => copyText(allScenePrompts, "prompts")}
        />

        <ExportItem
          label="All Voice Over"
          value={allVoiceOver}
          copied={copied === "voiceover"}
          onCopy={() => copyText(allVoiceOver, "voiceover")}
        />
      </div>
    </div>
  );
}

type ExportItemProps = {
  label: string;
  value: string;
  copied: boolean;
  onCopy: () => void;
};

function ExportItem({
  label,
  value,
  copied,
  onCopy,
}: ExportItemProps) {
  return (
    <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold text-white">
          {label}
        </h3>

        <Button
          onClick={onCopy}
          className="bg-zinc-800 hover:bg-zinc-700"
        >
          <Copy size={16} />
          {copied ? "Copied" : "Copy"}
        </Button>
      </div>

      <p className="mt-4 whitespace-pre-line rounded-xl bg-zinc-900 p-4 text-sm leading-7 text-zinc-300">
        {value}
      </p>
    </div>
  );
}